---
dataset:
  name: cifar100
  root: "../data"
  mean:
  - 0.5071
  - 0.4867
  - 0.4408
  std:
  - 0.2675
  - 0.2565
  - 0.2761
  padding: 4
train:
  warmup_epochs: 1
  epochs: 50
  batch_size: 128
val:
  batch_size: 256
  n_ff: 1
model:
  stem: false
  block: {}
optim:
  name: ACClip
  scheduler:
    name: MultiStepLR
    milestones:
    - 15
    - 25
    - 35
    gamma: 0.2
env: {}
